# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-UPIdbLQOPyXW3lEMtKkLPGXn_rTy_S
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Menambahkan background warna dan font custom
st.markdown(
    """
    <style>
        /* Menambahkan background warna */
        .reportview-container {
            background-color: #f0f0f0;  /* Ganti dengan warna yang kamu inginkan */
        }

        /* Mengubah font di seluruh aplikasi */
        body {
            font-family: 'Arial', sans-serif;
        }

        /* Mengubah tampilan button */
        .stButton > button {
            background-color: #4CAF50;  /* Ganti dengan warna pilihanmu */
            color: white;
            font-size: 15px;
            padding: 10px 24px;
            border-radius: 8px;
        }

        /* Mengubah tampilan tabel data */
        .stDataFrame tbody tr:nth-child(odd) {
            background-color: #e0e0e0;  /* Ganti dengan warna tabel */
        }

        .stDataFrame tbody tr:nth-child(even) {
            background-color: #f9f9f9;  /* Ganti dengan warna tabel */
        }

        /* Ganti warna pada sidebar */
        .sidebar .sidebar-content {
            background-color: #f0f0f0;
        }
    </style>
    """,
    unsafe_allow_html=True
)

# Judul aplikasi
st.title("Segmentasi Perusahaan Berdasarkan Transaksi Ekspor (K-Means Clustering)")

# Fungsi untuk meng-upload dataset
uploaded_file = st.file_uploader("Upload File PEB (.xlsx / .csv)", type=["xlsx", "csv"])

if uploaded_file is not None:
    try:
        # Memuat data dari file yang di-upload (Excel atau CSV)
        if uploaded_file.name.endswith("xlsx"):
            df = pd.read_excel(uploaded_file)
        else:
            df = pd.read_csv(uploaded_file)

        # Tampilkan data pertama untuk melihat preview
        st.subheader("Data Mentah")
        st.write(df.head(11))  # Menampilkan 5 baris pertama dari dataset

        # Preprocessing data: Hapus nilai yang kosong dan lakukan standarasi
        df_clean = df.copy()

        # Menghapus koma dan mengonversi kolom yang berisi angka dalam format string
        df_clean['FOB_USD'] = df_clean['FOB_USD'].replace({',': ''}, regex=True).astype(float)
        df_clean['Qty'] = df_clean['Qty'].replace({',': ''}, regex=True).astype(float)

        # Hapus nilai yang kosong setelah konversi
        df_clean.fillna(df_clean.mean(numeric_only=True), inplace=True)

        # Pastikan kolom FOB_USD dan Qty ada
        if "FOB_USD" in df_clean.columns and "Qty" in df_clean.columns:
            features = df_clean[["FOB_USD", "Qty"]]
            scaler = StandardScaler()
            scaled = scaler.fit_transform(features)

            # K-Means Clustering
            kmeans = KMeans(n_clusters=3, random_state=42)
            df_clean["Cluster"] = kmeans.fit_predict(scaled)

            # Visualisasi Scatter Plot untuk Clustering
            st.subheader("Visualisasi Clustering berdasarkan Nilai FOB dan Jumlah Transaksi")
            fig, ax = plt.subplots(figsize=(8, 6))
            sns.scatterplot(
                x=df_clean["FOB_USD"],
                y=df_clean["Qty"],
                hue=df_clean["Cluster"],
                palette="Set2",  # Ganti dengan palette yang lebih menarik
                s=100,
                ax=ax
            )
            ax.set_title("Visualisasi Clustering berdasarkan Transaksi Ekspor", fontsize=14)
            ax.set_xlabel("Nilai FOB (USD)", fontsize=12)
            ax.set_ylabel("Jumlah Transaksi", fontsize=12)
            st.pyplot(fig)

            # Hitung dan tampilkan Silhouette Score
            sil = silhouette_score(scaled, df_clean["Cluster"])
            st.write(f"**Silhouette Score:** {sil:.3f}")

            # Visualisasi Top 10 Perusahaan dengan Transaksi Terbanyak (Bar Plot)
            st.subheader("Top 10 Perusahaan dengan Transaksi Terbanyak")
            company_transactions = df_clean.groupby("Nama_Perusahaan")["Qty"].sum().reset_index()
            company_transactions.columns = ['Nama_Perusahaan', 'Jumlah_Transaksi']
            top_companies = company_transactions.sort_values(by="Jumlah_Transaksi", ascending=False).head(10)

            plt.figure(figsize=(12, 7))
            sns.barplot(x="Jumlah_Transaksi", y="Nama_Perusahaan", data=top_companies, palette="Blues")
            plt.title("Top 10 Perusahaan dengan Transaksi Terbanyak")
            plt.xlabel("Jumlah Transaksi")
            plt.ylabel("Nama Perusahaan")
            plt.tight_layout()
            st.pyplot(plt)

            # Tampilkan data dengan label cluster
            st.subheader("Data dengan Label Cluster")
            st.write(df_clean[["FOB_USD", "Qty", "Cluster"]])

        else:
            st.error("Dataset wajib mengandung kolom: FOB_USD dan Qty")
    except Exception as e:
        st.error(f"Error saat memproses file: {e}")
else:
    st.info("Silakan upload file untuk memulai analisis.")
