# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-UPIdbLQOPyXW3lEMtKkLPGXn_rTy_S
"""

!pip install streamlit
!pip install pyngrok
!pip install openpyxl

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# from sklearn.preprocessing import StandardScaler
# from sklearn.cluster import KMeans
# from sklearn.metrics import silhouette_score
# 
# st.title("Segmentasi Perusahaan Berdasarkan Transaksi Ekspor (K-Means Clustering)")
# 
# uploaded_file = st.file_uploader("Upload File PEB (.xlsx / .csv)", type=["xlsx", "csv"])
# 
# if uploaded_file:
#     try:
#         df = pd.read_excel(uploaded_file)
#     except:
#         df = pd.read_csv(uploaded_file)
# 
#     st.subheader("Data Mentah")
#     st.write(df.head())
# 
#     # Preprocessing
#     df_clean = df.copy()
#     df_clean.fillna(df_clean.mean(numeric_only=True), inplace=True)
# 
#     # Pastikan kolom tersedia
#     if "FOB_USD" in df_clean.columns and "Qty" in df_clean.columns:
# 
#         features = df_clean[["FOB_USD", "Qty"]]
#         scaler = StandardScaler()
#         scaled = scaler.fit_transform(features)
# 
#         # K-Means
#         kmeans = KMeans(n_clusters=3, random_state=42)
#         df_clean["Cluster"] = kmeans.fit_predict(scaled)
# 
#         st.subheader("Scatter Plot Clustering")
#         fig, ax = plt.subplots()
#         sns.scatterplot(
#             x=df_clean["FOB_USD"],
#             y=df_clean["Qty"],
#             hue=df_clean["Cluster"],
#             palette="viridis",
#             s=70,
#             ax=ax
#         )
#         st.pyplot(fig)
# 
#         sil = silhouette_score(scaled, df_clean["Cluster"])
#         st.write(f"**Silhouette Score:** {sil:.3f}")
# 
#         st.subheader("Data dengan Label Cluster")
#         st.write(df_clean[["FOB_USD", "Qty", "Cluster"]])
# 
#     else:
#         st.error("Dataset wajib mengandung kolom: FOB_USD dan Qty")
# else:
#     st.info("Silakan upload file untuk memulai analisis.")
#